export const malaysiaStatesAndCities = {
  Johor: [
    "Batu Pahat",
    "Johor Bahru",
    "Kluang",
    "Kota Tinggi",
    "Kulai",
    "Mersing",
    "Muar",
    "Pontian",
    "Segamat",
    "Tangkak",
  ],
  Kedah: [
    "Alor Setar",
    "Bandar Baharu",
    "Kubang Pasu",
    "Kulim",
    "Langkawi",
    "Padang Terap",
    "Pendang",
    "Sungai Petani",
    "Yan",
  ],
  Kelantan: [
    "Bachok",
    "Gua Musang",
    "Kota Bharu",
    "Kuala Krai",
    "Machang",
    "Pasir Mas",
    "Pasir Puteh",
    "Tanah Merah",
    "Tumpat",
  ],
  Melaka: [
    "Alor Gajah",
    "Asahan",
    "Jasin",
    "Masjid Tanah",
    "Melaka City",
    "Merlimau",
  ],
  "Negeri Sembilan": [
    "Bahau",
    "Kuala Pilah",
    "Nilai",
    "Port Dickson",
    "Rembau",
    "Seremban",
    "Tampin",
  ],
  Pahang: [
    "Bentong",
    "Cameron Highlands",
    "Jerantut",
    "Kuantan",
    "Lipis",
    "Pekan",
    "Raub",
    "Rompin",
    "Temerloh",
  ],
  Perak: [
    "Batu Gajah",
    "Ipoh",
    "Lumut",
    "Sitiawan",
    "Slim River",
    "Taiping",
    "Tapah",
    "Teluk Intan",
    "Kampar",
  ],
  Perlis: ["Arau", "Kangar", "Kuala Perlis", "Padang Besar"],
  "Pulau Pinang": [
    "Bayan Lepas",
    "Bukit Mertajam",
    "Butterworth",
    "George Town",
    "Kepala Batas",
    "Nibong Tebal",
    "Seberang Perai",
  ],
  Sabah: [
    "Kota Kinabalu",
    "Keningau",
    "Kudat",
    "Lahad Datu",
    "Ranau",
    "Sandakan",
    "Semporna",
    "Tawau",
  ],
  Sarawak: [
    "Bintulu",
    "Kapit",
    "Kuching",
    "Limbang",
    "Miri",
    "Sarikei",
    "Sibu",
    "Sri Aman",
  ],
  Selangor: [
    "Ampang",
    "Kajang",
    "Klang",
    "Petaling Jaya",
    "Shah Alam",
    "Rawang",
    "Selayang",
    "Subang Jaya",
  ],
  Terengganu: [
    "Besut",
    "Dungun",
    "Hulu Terengganu",
    "Kemaman",
    "Kuala Terengganu",
    "Marang",
    "Setiu",
  ],
  "W.P. Kuala Lumpur": ["Kuala Lumpur"],
  "W.P. Labuan": ["Labuan"],
  "W.P. Putrajaya": ["Putrajaya"],
};
